export enum LoggingPreferencesEnum {
  LEVEL = 'LOGGER.LEVEL',
  DIRECTORY = 'LOGGER.DIRECTORY',
  FILENAME = 'LOGGER.FILENAME',
  USE_SINGLE_FILE = 'LOGGER.USE_SINGLE_FILE',
  USE_CONSOLE = 'LOGGER.USE_CONSOLE',
  USE_ROTATION_FILE = 'LOGGER.USE_ROTATION_FILE',
}
