language: node_js
env:
  - NODE_ENV=test

branches:
  only:
    - microservices

services:
  - docker

before_script:
  - sudo /etc/init.d/postgresql stop
  - mkdir ./config/ssl
  - openssl req -new -x509 -newkey rsa:4096 -keyout ./config/ssl/musicserver.key -out ./config/ssl/musicserver.crt -days 365 -subj "/C=DE/ST=Bavaria/L=Test/O=Teste/OU=DE/CN=www.example.com" -nodes

script:
  - cd ./services/logger/integration_test && bash ./test.sh

deploy:
  provider: script
  script:
    - ./docker_build.sh
    - ./docker_push.sh
  on:
    branch: microservices
