language: node_js
env:
  - NODE_ENV=test

branches:
  only:
    - microservices

services:
  - docker

before_script:
  - sudo /etc/init.d/postgresql stop

script:
  - cd ./services/logger/integration_test && bash ./gittest.sh
