language: node_js
env:
  - NODE_ENV=test

branches:
  only:
    - microservices

services:
  - docker

before_script:
  - sudo /etc/init.d/postgresql stop
  - mkdir $TRAVIS_BUILD_DIR/config/ssl
  - openssl req -new -x509 -newkey rsa:4096 -keyout ./config/ssl/musicserver.key -out ./config/ssl/musicserver.crt -days 365 -subj "/C=DE/ST=Bavaria/L=Test/O=Teste/OU=DE/CN=www.example.com" -nodes

script:
  - cd $TRAVIS_BUILD_DIR/services/logger/integration_test && bash ./test.sh


before_deploy:
  - cd $TRAVIS_BUILD_DIR

deploy:
  provider: script
  skip_cleanup: true
  script: bash docker_build.sh
  on:
    branch: microservices
